[project]
name = "agi-house-agents-hack"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "livekit-agents>=1.4.1",
    "livekit-plugins-deepgram>=1.4.1",
    "livekit-plugins-openai>=1.4.1",
    "livekit-plugins-silero>=1.4.1",
    "python-dotenv>=1.2.1",
]
